- max_len: 30
- vocab_size: 27 #26 letters + _
- embedding_dim: 4
- n_lstm: 2
- hidden_dim: 30
- dense_dim_lstm: 60
- dense_dim_guessed: 60
- n_dense_guessed: 2
- dense_dim_final: 100
- dense_dim_output: 26
- use_embedding: True